version: "3.1"
networks:
  web:
    external: true
  internal:
    external: false
services:
  node-testnet:
    image: node:16-alpine
    container_name: "referral-program-backend"
    restart: always
    ports:
      - 1990:5000
    volumes:
      - ./:/home/node/app
    networks:
      - internal
    working_dir: /home/node/app
    command: >
      sh -c "npm i -g pm2 && yarn && pm2-runtime app.js --watch"